#ifndef AURIC_DRIFT_H
#define AURIC_DRIFT_H

/* This file is auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct CDriftFeatures {
  float bpm;
  int32_t key;
  float energy;
  float brightness;
  float dynamic_range;
  char *error;
} CDriftFeatures;

typedef struct CDriftConfig {
  uint32_t artist_separation;
  uint32_t album_separation;
  uint32_t genre_separation;
  double freshness_decay_hours;
  double skip_penalty_weight;
  double discovery_boost;
  bool genre_transition_smoothing;
  bool harmonic_mixing;
  double harmonic_weight;
  bool bpm_continuity;
  float max_bpm_delta;
  bool energy_smoothing;
  float max_energy_delta;
  bool brightness_smoothing;
  float max_brightness_delta;
} CDriftConfig;

struct CDriftFeatures auric_drift_analyze_file(const char *path);

struct CDriftConfig auric_drift_default_config(void);

void auric_drift_free_string(char *s);

#endif  /* AURIC_DRIFT_H */
